name: smooth_charts_example
description: Example app for smooth_charts.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_charts:
    path: ../

flutter:
  uses-material-design: true
